require:
  - rubocop-rspec
  - rubocop-rails

Rails:
  Enabled: true

AllCops:
  NewCops: enable
  EnabledByDefault: true
  Exclude:
    - 'node_modules/**/*'
    - 'db/schema.rb'
    - 'bin/*'
    - 'config/boot.rb'

Style/Documentation:
  Enabled: false

Style/MissingElse:
  Enabled: false

Style/SymbolArray:
  Exclude:
    - 'db/schema.rb'

Layout/LineLength:
  Max: 120
  Exclude:
    - 'config/initializers/devise.rb'

Metrics/CyclomaticComplexity:
  Max: 8

Metrics/PerceivedComplexity:
  Max: 8

Metrics/AbcSize:
  Max: 17

Bundler/GemComment:
  Enabled: false

Style/Copyright:
  Enabled: false

Lint/ConstantResolution:
  Enabled: false

Style/DocumentationMethod:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 30
  Exclude:
    - 'spec/**/*'

Metrics/ClassLength:
  Max: 300

Metrics/ModuleLength:
  Max: 300
  Exclude:
    - '**/*_spec.rb'

RSpec/MultipleExpectations:
  Enabled: false

Style/StringHashKeys:
  Exclude:
    - '**/*_spec.rb'

Style/MethodCallWithArgsParentheses:
  EnforcedStyle: 'require_parentheses'
  IgnoredPatterns:
    - 'puts'
    - 'to'
    - 'render'
    - 'redirect_to'
    - 'raise'
  Exclude:
    - 'db/migrate/*'

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent
